### ISSUE TITLE
Update the readme (or don't build from scratch)

### ISSUE THREAD

**Issue by darioseidl** [brunopadz/mkcert-docker#3]
The command in the readme doesn't seem to be correct, as it uses `/bin/sh`, while the Dockefile is built `FROM scratch`, which doesn't include `sh` or anything but the `mkcert` binary.

```
$ docker run -v $PWD:/root/.local/share/mkcert brunopadz/mkcert-docker:latest \
/bin/sh -c "mkcert -install && \
mkcert -cert-file /root/.local/share/mkcert/mkcert.pem \
-key-file /root/.local/share/mkcert/mkcert.key localhost.dev"
```
> docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown.
ERRO[0000] error waiting for container:          

Looking at the Dockerfile history, an older version of the image was built from `golang:1.12-alpine`, I guess the command worked back then.

I was able to run the current Docker image with the following command in instead:

```
docker run -v $HOME/.local/share/mkcert:/.local/share/mkcert brunopadz/mkcert-docker:latest\     
 ./mkcert -cert-file /.local/share/mkcert/mkcert.pem -key-file /.local/share/mkcert/mkcert.key localhost
```

**Comment by brunopadz** [comment]
Hey @darioseidl, thanks for the info.

Could you open a PR in order to fix it?

**Comment by darioseidl** [comment]
Hi @brunopadz! Sure, I created a [PR that builds the image from alpine](https://github.com/brunopadz/mkcert-docker/pull/4). This makes the image bigger but much easier to use.

**Comment by brunopadz** [comment]
Just pushed the images updated. Feel free to open another issue in case of any errors. 

Thanks once again, man. :)
